name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
language: python

python:
  - "3.7"
  - "3.8"

os: osx

jobs:

  - run: pip install -r requirements.txt

  - run: flake8 . --ignore E501 --exclude='test_*.py'

  - run: pylint --disable=C0415,C0103 utils models routes

  - run: pytest
